global:
  scrape_interval: 5s
scrape_configs:
  - job_name: gitlab
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: /-/metrics
    static_configs:
      - targets:
        - gitlab:443